### ISSUE TITLE
MacOS Sonoma 14.3 - PreForget disappearing from menu bar and refusing to open (?)

### ISSUE THREAD

**Issue by capillarys** [asj9469/PreForget#1]
This is the second time it's happened, so I've decided to make an issue for it! 

I have PreForget as one of my login items, so it's usually open all the time on my menu bar. For some reason it's disappeared, and when I go to launchpad to find the app and open it manually, all that shows up is this:

![Screenshot](https://github.com/asj9469/PreForget/assets/101748822/b5548be2-8552-4a87-a562-d0734b40c6dd)

The last time this happened, I was a bit stressed and was worried that it could be related to me having too many browser tabs open, or something to that effect? I put my Mac down for a bit and when I returned, PreForget was back again, right as rain. I just assumed it solved itself. I'd like to give more information too, but it refused to open even when I go to my Applications folder and use "right-click open". 

I did manage to open it by right-clicking PreForget, clicking "Show Package Contents", "Contents", "MacOS" and opening the PreForget Unix Executable File in Terminal, but the moment I close that Terminal window, PreForget yeets. Interestingly, when I add new tasks while having PreForget open through terminal, this shows up:

`2024-02-18 00:15:01.184 PreForget[86095:4437436] NSWindow does not support nonactivating panel styleMask 0x80`

Also for reference, I downloaded PreForget via AppStore, and I don't think there's any updates I've missed. I suppose factors that could lead to this might be: too many windows/tabs open, computer plugged to power source, computer not having been shut down/restarted in a while... 

Thank you so much! I hope I've offered enough information about this issue, and that you can 1. replicate it and 2. figure out a way to fix it <3 Or maybe let me know if it's something on my end I need to be more careful with!

**Comment by asj9469** [comment]
Hey, thanks for reaching out!

I'll try to look into the source code and see if there's any internal issues. This was a bug that happened time to time during the development phase as well, but it occured so rarely that I thought it was just an issue on my side.

The blank screen that pops up when you manually open the app is just a dummy window. I've been trying to find a way to get rid of it, but hard to figure out where that's coming from. I appreciate you for providing the terminal error -- I'll try to look into it as well.

One question: when this error happens, are your tasks still there when it launches again? 

Also, thank you for using PreForget! If you find the app helpful or if there's any other feedback you'd like to share, I would greatly appreciate it if you could leave a quick review on the app store!

**Comment by capillarys** [comment]
Oh hi, thank you for the quick response! Whew I'm glad it's not just me, even though we still dunno where it's coming from. Actually in the daytime today PreForget showed up fine, but when my computer changed to dark mode (I have dark mode set up based on sunset times) I think PreForget disappeared? Still hasn't reappeared yet, so I've opened it through Terminal again! My tasks seem to still be here.

Thank you so much for making PreForget! I'd been looking for a nice, visually appealing, not too stressful to use menu bar to-do app, so I'm very very happy I waded through macmenubar.com and found PreForget. Is it better to share feedback here directly or on the App Store? One feature (?) I think would be helpful is maybe having our past, completed to-dos stored in a list somewhere, somehow? I don't want it to all pile up in the UI, but maybe having it stored somewhere in saves or wherever, so the more tech savvy people who want to find it can access their completed tasks, as well as maybe info like when it was added and when it was completed. But I'd also understand if that's too much to ask 🙏 

Also! While I'm really not much of a coder, I noticed you had "implement AI to generate new messages" in your Future Plans. I'm no AI but I'd be interested in contributing new messages, if you need 'em! Thank you so much once again :3

**Comment by asj9469** [comment]
You're right, I did have some issues when changing between the light, dark modes. When I tested it on my friend's device, light mode didn't show the icon on the menu bar (background was too bright, etc.). I think I might have to look into the light/dark modes first. Thanks for narrowing down the scope!

It would be super helpful if you could share why you like PreForget or what makes you keep using it on the App Store :D This will help other people to get a grasp of why PreForget is special and more people will be able to use it 🎉

Feature suggestions are most welcome on GitHub! You can open a new issue here and label it "enhancement". This will show up publicly and I'll be able to quickly identify which ones are for new features, which ones are for bugs, and so on. 
-- Would you be able to open an issue "Accessing Completed Tasks," label it with "enhancement," and just briefly explain like you did just now? It will help me keep track of my to-dos for PreForget, and we can discuss about it more there!

I'll try to see if I can make a board or some place where everyone can give suggestions for new messages! The AI implementation plan is pushed away for now because we would then have to deal with payment plans (AI credits), and I just want PreForget to be a simple app that anyone can use. But definitely! I could use some help for new message options. I'm glad that the message feature is something users actually like!

**Comment by capillarys** [comment]
I'll make an enhancement issue soon!! And I'll be sure to review <3

By the way, you asked this:  
> One question: when this error happens, are your tasks still there when it launches again?  

And I've found that tasks added when I open via Terminal do not transfer over to when PreForget opens normally!

![Screenshot 2024-02-21 at 14 23 28](https://github.com/asj9469/PreForget/assets/101748822/af0a912a-c735-4fc8-9bb4-13b78069ec20)

![Screenshot 2024-02-21 at 14 23 31](https://github.com/asj9469/PreForget/assets/101748822/89c76d1c-eec2-41d4-8d98-e7ee3fcc4e53)

The first screenshot has tasks I added when I opened via Terminal (the Unix Executable File), and the second is the bottom of the task list of when PreForget stopped bugging and opened normally. I think that might be relevant to what you were asking? I have no clue where anything is stored, but at least now we know tasks saved via Terminal won't show up in the normal PreForget, nor does progress in the Terminal version transfer over. 

I'd test if the opposite was true (like if I add a task in the normal PreForget, does it show up in the Terminal/Unix Executable version?) if I could, but right now my normal PreForget is only showing the dummy window again. And my computer isn't even in dark mode, so I'm not too sure what the issue is here today :( Anywho best of luck in puzzling this out!

**Comment by asj9469** [comment]
Right, thank you so much for this! I've been trying to look through the source code, but I'm having a hard time pinpointing the issue...

If the issue happens again can you try restarting your mac instead of opening it through the terminal? I'm trying to see if this issue has more to do with the device than the app itself (not saying that it's your computer's problem, but it could be a conflict between the app and the mac system itself).

I greatly appreciate your contribution!

**Comment by asj9469** [comment]
Update: fixed code to remove the dummy window

**Comment by asj9469** [comment]
1. dummy window removal included in the new update
2. when it doesn't open, we have to manually restart the app - there's no work around for this :(
3. the issue with icon disappearing when changing light/dark mode - I believe this is an issue with the system itself... can't fix this with code unless we change the icon :(
