### ISSUE TITLE
Accessing Completed Tasks

### ISSUE THREAD

**Issue by capillarys** [asj9469/PreForget#2]
I think it would be helpful to have completed tasks be saved and accessible, ideally with information about when it was added and completed! I'm not sure if it's better for completed tasks to be accessible in the menu bar app itself (maybe a toggle for them to be shown?), or for it to be saved in some sort of maybe .json, .csv or similar file? 

Here's a very crude and badly made visualisation of what it could be like! (I also included some changes in keyboard shortcuts - I believe command comma is the "universal" setting/preference shortcut, so maybe that can be used instead? And I suggested command D for done tasks, but ofc you can go with whatever works best!)

![Screenshot 2024-02-21 at 16 15 12](https://github.com/asj9469/PreForget/assets/101748822/95a3825e-8021-481a-930b-71bd25b2eaa7)

Or maybe it can even be an option within the settings itself, to either lead you to an external list of completed tasks, or maybe actually play with the whole window concept - completed tasks open in app window?

I hope these ideas make sense! It'd be quite helpful to me to be able to access completed tasks, while not having the completed tasks pile on in the existing UI (which would be cumbersome and kind of stressful to use). Thank you once again for your hard work!

Edit: By the way I don't think I'm able to add labels to issues :( Please label this as enhancement! Or maybe look into how to allow users to label issues as bug/enhancement 🙏

**Comment by asj9469** [comment]
Oh, I didn't know I was the only one who could label issues LOL - will look into that
Also, thank you for pointing out the settings command. I don't use Apple products as my main devices (PreForget is a hobby project I did on a macbook I somehow acquired), so I appreciate your insight.

I'll try to see if PreForget can store the information on an external file. Like make keep an active .json file that logs all the completed tasks. I'm leaning more towards the external file option because storing all the completed tasks on the app (regardless of if it's hidden from view or not) could cause lagging & more issues later on (all these tasks are stored locally on the users' device).

I'll try to check in with the project and try to work on it on my free time!

**Comment by asj9469** [comment]
UPDATE:

Apologies for the delay. I am currently working on a history popup window within the app where users can view their completed tasks. Users will be able to delete items from the history view as well to clear up memory.

**Comment by asj9469** [comment]
Feature added in new update
